---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: openfaas-ingress
  namespace: openfaas
  annotations:
    {{ if .TLS }}
    certmanager.k8s.io/acme-challenge-type: dns01
    certmanager.k8s.io/acme-dns01-provider: {{.DNSService}}
    certmanager.k8s.io/cluster-issuer: letsencrypt-{{.IssuerType}}
    kubernetes.io/tls-acme: "true"
    {{ end }}
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/limit-connections: "20"
    nginx.ingress.kubernetes.io/limit-rpm: "600"
  labels:
    app: faas-netesd
spec:
  {{ if .TLS }}
  tls:
  - hosts:
    - '*.{{.RootDomain}}'
    secretName: wildcard-{{.RootDomain}}-cert
  {{ end }}
  rules:
  - host: '*.{{.RootDomain}}'
    http:
      paths:
      - path: /
        backend:
          serviceName: of-router
          servicePort: 8080
  - host: 'gateway.{{.RootDomain}}'
    http:
      paths:
      - path: /
        backend:
          serviceName: gateway
          servicePort: 8080
