environment:
  validate_hmac: "1"
# URLs
  gateway_url:  http://gateway.openfaas:8080/
  gateway_public_url: {{.Scheme}}://cloud.{{.RootDomain}}/
  audit_url: http://gateway.openfaas:8080/function/audit-event
  # Remove gateway_pretty_url if not using pretty URL
  gateway_pretty_url: {{.Scheme}}://user.{{.RootDomain}}/function
  # Add your custom templates by adding a coma separated URL, i.e. extend the current value with:
  # ", https://github.com/custom/template.git, https://github.com/custom/template2.git"
  custom_templates: {{ .CustomTemplates }}

# Security
  customers_url: "{{.CustomersURL}}"
  basic_auth: true
  secret_mount_path: /var/openfaas/secrets

# Container builder
  repository_url: {{.Registry}}
  push_repository_url: {{.Registry}}
  builder_url: http://of-builder.openfaas:8080/

# Logging
  s3_url: {{.S3.Url}}
  s3_region: {{.S3.Region}}
  s3_tls: {{.S3.TLS}}
  s3_bucket: {{.S3.Bucket}}

# Function policy
  readonly_root_filesystem: {{.GatewayFunctionConfig.RORootFS}}
  scaling_min_limit: {{.GatewayFunctionConfig.ScalingMin}}
  scaling_max_limit: {{.GatewayFunctionConfig.ScalingMax}}
  prometheus_host: prometheus.openfaas
  prometheus_port: 9090
  metrics_window: 60m

# Dockerfile language support
  enable_dockerfile_lang: {{.EnableDockerfileLang}}

  # Set the build branch to be used by ofc
  build_branch: {{.BuildBranch}}

